#!/usr/bin/env bash
set -ex

cd $(dirname $0)

# --------------------------------------
# Prepare environment
# --------------------------------------

source ./config
tmp="$PWD/result"
key="$(readlink -f $(basename $0))/git-cirrus-deploy-key"
out="${ENV_OUT}"

if [ -d "$out" ]; then
    set +x
    echo "Environment target directory already exists:" >&2
    echo "  ${out}"
    echo "Maybe it's alreayd installed?" >&2
    echo "Either:" >&2
    echo "  1. Increment ENV_BUILD in ./config" >&2
    echo "  2. rm -rf ${out}" >&2

    exit 1
fi

# When running interactively, enter bash on error
if tty -s
then
    echo "INFO: Enabling bash shell on error"
    function on_err {
        echo "!!! ERROR DURING BUILD !!!" >&2
        bash
    }
    trap on_err ERR
fi

# --------------------------------------
# Create environment
# --------------------------------------
mkdir -p "${ENV_OUT}/bin"
ln -s "${CIRRUS_OUT}/bin/cirrus" "${ENV_OUT}/bin/cirrus"
sed s,@MPIRUN@,${PETSC_OUT}/bin/mpirun, src/mpi-cirrus > "${ENV_OUT}/bin/mpi-cirrus"
chmod +x "${ENV_OUT}/bin/mpi-cirrus"
