#!/usr/bin/env bash
set -ex

cd $(dirname $0)

# --------------------------------------
# Prepare environment
# --------------------------------------

source ./config
tmp="$PWD/result"
out="${CIRRUS_OUT}"
src="$tmp/git-cirrus-${CIRRUS_COMMIT}"

if [ -d "$out" ]; then
    set +x
    echo "Cirrus target directory already exists:" >&2
    echo "  ${out}"
    echo "Maybe it's alreayd installed?" >&2
    echo "Either:" >&2
    echo "  1. Increment CIRRUS_BUILD in ./config" >&2
    echo "  2. rm -rf ${out}" >&2

    exit 1
fi

# When running interactively, enter bash on error
if tty -s
then
    echo "INFO: Enabling bash shell on error"
    function on_err {
        echo "!!! ERROR DURING BUILD !!!" >&2
        bash
    }
    trap on_err ERR
fi

# --------------------------------------
# Clone Cirrus
# --------------------------------------
if ! [[ -d "$src" ]]
then
    git clone "${CIRRUS_URL}" "$src"
fi

if ! [[ -f "$tmp/six-*-.whl" ]]
then
    python3 -m pip download -d "$tmp" six
fi

# --------------------------------------
# Build Cirrus
# --------------------------------------
cd $src/src/cirrus
git reset --hard
git clean -xdf

export PETSC_DIR="$PETSC_OUT"
export PETSC_ARCH=
export PYTHONPATH="$tmp/six-*-.whl"

make cirrus
make test
install -D cirrus $out/bin/cirrus
