#!/usr/bin/env bash
set -ex

cd $(dirname $0)

# --------------------------------------
# Prepare environment
# --------------------------------------

source ./config
tmp="$PWD/result"
key="$(readlink -f $(basename $0))/git-cirrus-deploy-key"
out="${CIRRUS_OUT}"

if [ -d "$out" ]; then
    set +x
    echo "Cirrus target directory already exists:" >&2
    echo "  ${out}"
    echo "Maybe it's alreayd installed?" >&2
    echo "Either:" >&2
    echo "  1. Increment CIRRUS_BUILD in ./config" >&2
    echo "  2. rm -rf ${out}" >&2

    exit 1
fi

# When running interactively, enter bash on error
if tty -s
then
    echo "INFO: Enabling bash shell on error"
    function on_err {
        echo "!!! ERROR DURING BUILD !!!" >&2
        bash
    }
    trap on_err ERR
fi

# --------------------------------------
# Clone Cirrus
# --------------------------------------
mkdir -p $tmp
git clone ${CIRRUS_URL} $tmp/git-cirrus-${CIRRUS_COMMIT}

# --------------------------------------
# Build Cirrus
# --------------------------------------
cd $tmp/git-cirrus/src/cirrus-${CIRRUS_COMMIT}

export PETSC_DIR="${STORE}/petsc-${PETSC_VERSION}-${PETSC_BUILD}+$(printf %.8s ${PETSC_COMMIT})"
export PETSC_ARCH=

make UPDATE_PROVENANCE=0 cirrus
make test
install -D cirrus $out/bin/cirrus
