#!/usr/bin/env bash
set -ex

cd $(dirname $0)

# --------------------------------------
# Prepare environment
# --------------------------------------

# When running interactively, enter bash on error
if tty -s
then
    echo "INFO: Enabling bash shell on error"
    function on_err {
        echo "!!! ERROR DURING BUILD !!!" >&2
        bash
    }
    trap on_err ERR
fi

source ./config
tmp="$PWD/result"
out="${STORE}/petsc-${PETSC_VERSION}-${PETSC_BUILD}+$(printf %.8s ${PETSC_COMMIT})"

if [ -d "$out"]; then
    echo "PETSC target directory already exists:" >&2
    echo "  ${out}"
    echo "Maybe it's already installed?" >&2
    echo "Either:" >&2
    echo "  1. Increment PETSC_BUILD in ./config" >&2
    echo "  2. rm -rf ${out}" >&2

    exit 1
fi

# --------------------------------------
# Clone PETSC
# --------------------------------------
mkdir -p $tmp
curl -L $PETSC_URL -o $tmp/git-petsc.zip
unzip $tmp/git-petsc.zip -d $tmp/git-petsc

# --------------------------------------
# Build petsc
# --------------------------------------
cd $tmp/git-petsc/petsc-${PETSC_COMMIT}

export PETSC_DIR=$PWD
export PETSC_ARCH=gnu-c-opt

./configure                                  \
    --DESTDIR=$tmp                           \
    --COPTFLAGS="-O3"                        \
    --CXXOPTFLAGS="-O3"                      \
    --FOPTFLAGS="-O3"                        \
    --download-fblaslapack=yes               \
    --download-hdf5=yes                      \
    --download-hypre=yes                     \
    --download-openmpi=yes                   \
    --download-ptscotch=yes                  \
    --download-hdf5-fortran-bindings=yes     \
    --with-debugging=0                       \
    --prefix=$out

make all
make check
make install
