#!/usr/bin/env bash
# This script assumes that it's being ran inside of a
# quay.io/pypa/manylinux2014_x86_64 OCI image.
#
# To run manually:
# podman run --rm -it -v$PWD:$PWD:z -w$PWD quay.io/pypa/manylinux2014_x86_64 ./build_using_manylinux2014
set -ex

petsc_rev="v3.19.1"
pflotran_ogs_version="1.8"
pflotran_ogs_rev="11"

petsc_url="https://gitlab.com/petsc/petsc.git"
pflotran_ogs_url="https://bitbucket.org/opengosim/pflotran_ogs_${pflotran_ogs_version}.git"

out="$PWD/result"

# Remove output if previously generated
rm -rf $out

# --------------------------------------
# Clone
# --------------------------------------
mkdir $out
git clone --depth=1 --branch="${petsc_rev}" -- "${petsc_url}" $out/.git-petsc
git clone --depth=1 --branch="sv${pflotran_ogs_rev}" -- "${pflotran_ogs_url}" $out/.git-pflotran_ogs

# --------------------------------------
# Prepare environment
# --------------------------------------

# When running interactively, enter bash on error
if tty -s
then
    echo "INFO: Enabling bash shell on error"
    function on_err {
        echo "!!! ERROR DURING BUILD !!!" >&2
        bash
    }
    trap on_err ERR
fi

# --------------------------------------
# Build petsc
# --------------------------------------
cd $out/.git-petsc

export PETSC_DIR=$PWD
export PETSC_ARCH=gnu-c-opt

./configure                                  \
    --CFLAGS="-O3"                           \
    --CXXFLAGS="-O3"                         \
    --FFLAGS="-O3"                           \
    --download-fblaslapack=yes               \
    --download-hdf5=yes                      \
    --download-hypre=yes                     \
    --download-openmpi=yes                   \
    --download-ptscotch=yes                  \
    --download-hdf5-fortran-bindings=yes     \
    --with-debugging=0                       \
    --prefix=$out

make all
make check
make install

# --------------------------------------
# Build PFLOTRAN-OGS
# --------------------------------------
cd $out/.git-pflotran_ogs/src/pflotran

make UPDATE_PROVENANCE=0 pflotran
make check
install -D pflotran $out/bin/pflotran
