#!/usr/bin/env bash
set -e

cd $(dirname $0)

# --------------------------------------
# Prepare environment
# --------------------------------------

current_area_short=$(hostname | grep -oE "^[^-]+")

# --------------------------------------
# Sync with all areas
# --------------------------------------
areas=(
  be-grid01.be.statoil.no
  st-grid01.st.statoil.no
  s268-lckm.s268.oc.equinor.com  # master node of CCS CycleCloud
  tr-grid01.tr.statoil.no
  hou-grid01.hou.statoil.no
  # rio-grid01.rio.statoil.no  # I have no home directory ~Zohar
  stjohn-grid01.stjohn.statoil.no
)

for area in "${areas[@]}"
do
  echo "# --------------------------------------"
  area_short=$(echo "$area" | grep -oE "^[^-]+")
  echo "Deploying to: $area"
  rsync "src/runcirrus" "$area:/prog/pflotran/bin/_runcirrus"
done
