destination: /opt/karsk/test
main-package: hello
entrypoint: bin/binary.sh
build-image: Containerfile
tests: ./karsk_tests/

packages:
  - name: hello
    version: 1.0.0
    src:
      type: file
      path: binary.sh
    build: |
      mkdir -p $out/bin
      cp $src $out/bin/
