FROM registry.access.redhat.com/ubi8/ubi:latest

RUN dnf -y groupinstall "Development Tools"
RUN dnf -y install which
RUN dnf -y install python3.11
RUN dnf -y install gcc-gfortran
RUN dnf -y install git
