# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 9

    # PyPA CentOS 7-based image: https://github.com/pypa/manylinux
    - name: Build using manylinux2014 image
      uses: docker://quay.io/pypa/manylinux2014_x86_64
      with:
        entrypoint: /github/workspace/build_using_manylinux2014

    - name: Upload output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-redhat-linux
        path: pflotran_ogs*.tar.xz
